apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandoor-backend
  namespace: wandoor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wandoor-backend
  template:
    metadata:
      labels:
        app: wandoor-backend
    spec:

      # -- INIT CONTAINER (Download java agent)
      initContainers:
        - name: download-otel-agent
          image: busybox
          command:
            - sh
            - -c
            - >
              wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
              -O /otel/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: backend
          image: jrtr1/wandoor-backend-app:backend-175322ce28932d9a6c48d46f0e798978404cf699
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP

          env:
            # ============================
            #      DATABASE CONFIG
            # ============================
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@10.148.15.217:1521/wandoor_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "wandoor"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            - name: SERVER_PORT
              value: "8081"

            # ============================
            #      REDIS CONFIG
            # ============================
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "rediswandoor"

            # ============================
            #      OTEL TRACING CONFIG
            # ============================
            # Endpoint harus ke OTEL Collector, bukan Tempo!
            - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
              value: "grpc"

            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"

            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=wandoor-backend,service.namespace=wandoor"

            - name: OTEL_TRACES_SAMPLER
              value: "always_on"

            # Jalankan Java dengan agent OTEL
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"


          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      volumes:
        - name: otel-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wandoor
spec:
  selector:
    app: wandoor-backend
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30080
      protocol: TCP
