apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandoor-backend
  namespace: wandoor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wandoor-backend
  template:
    metadata:
      labels:
        app: wandoor-backend
    spec:
      initContainers:
        - name: download-otel-agent
          image: busybox
          command:
            - sh
            - -c
            - >
              wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
              -O /otel/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: backend
          image: jrtr1/wandoor-backend-app:backend-366ba29cf0983c2b10516a1b87391fe724f885f1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@10.148.15.217:1521/wandoor_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "wandoor"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SERVER_PORT
              value: "8081"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "rediswandoor"

            # ðŸ”¥ Tambahan untuk traces
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://10.148.15.215:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=wandoor-backend"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"

          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      volumes:
        - name: otel-agent
          emptyDir: {}
