apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandoor-backend
  namespace: wandoor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wandoor-backend
  template:
    metadata:
      labels:
        app: wandoor-backend
    spec:
      containers:
        - name: backend
          image: jrtr1/wandoor-backend-app:backend-1ebb2e547f82ca26c056c01d6b60cb01cd2d1194
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@10.148.15.217:1521/wandoor_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "wandoor"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SERVER_PORT
              value: "8081"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "rediswandoor"

            # OTEL minimal
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=wandoor-backend"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"

          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      volumes:
        - name: otel-agent
          emptyDir: {}
